version: '3.8'
services:
  component-library:
    build:
      context: ./component-library
    ports:
      - "3000:3000"

  react-webcomponent:
    build:
      context: ./react-webcomponent
    ports:
      - "3001:3001"

  consumer-app:
    build:
      context: ./consumer-app
    ports:
      - "4000:4000"
    depends_on:
      - component-library

  nextjs-consumer-app:
    build:
      context: ./nextjs-consumer-app
    ports:
      - "4001:4001"
    depends_on:
      - component-library

  angularjs-consumer-app:
    build:
      context: ./angularjs-consumer-app
    ports:
      - "4002:4002"
    depends_on:
      - component-library
